"""empty message

Revision ID: 05e2fa036256
Revises: 9d528aeafc98
Create Date: 2025-01-30 16:19:29.924551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e2fa036256'
down_revision = '9d528aeafc98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
