"""empty message

Revision ID: 5458f8d8db28
Revises: c53f5a1a07e2
Create Date: 2025-01-30 18:55:12.646180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5458f8d8db28'
down_revision = 'c53f5a1a07e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('rate')

    op.create_table('rating',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rater_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_ratings', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rating_counts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rater_id'], ['user.id'], name='rating_rater_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='rating_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='rating_pkey')
    )
    # ### end Alembic commands ###
