"""empty message

Revision ID: 647617ac5958
Revises: bba919f40baa
Create Date: 2025-01-11 13:34:19.729251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647617ac5958'
down_revision = 'bba919f40baa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=250), nullable=False))
        batch_op.drop_column('hashed_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashed_password', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
