"""empty message

Revision ID: c53f5a1a07e2
Revises: 9792060bdf89
Create Date: 2025-01-30 17:27:58.760058

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c53f5a1a07e2'
down_revision = '9792060bdf89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_ratings', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rating_counts', sa.Integer(), nullable=True))
        batch_op.drop_column('total_rate')
        batch_op.drop_column('rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_rate', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('rating_counts')
        batch_op.drop_column('total_ratings')

    # ### end Alembic commands ###
